services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'

  rabbitmq:
    image: 'rabbitmq:3-management' # Web paneli olan RabbitMQ imajı
    ports:
      - '5672:5672' # AMQP port (uygulamalar arası iletişim)
      - '15672:15672' # Web arayüzü portu (tarayıcıdan erişim)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest