services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'

  rabbitmq:
    image: 'rabbitmq:3-management' # Web paneli olan RabbitMQ imajı
    ports:
      - '5672:5672' # AMQP port (uygulamalar arası iletişim)
      - '15672:15672' # Web arayüzü portu (tarayıcıdan erişim)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - '5044:5044'
      - '5000:5000'
    depends_on:
      - elasticsearch
    networks:
      - elk

  app:
    build:
      context: .
    container_name: dailyreader-app
    depends_on:
      - postgres
      - rabbitmq
      - logstash
    ports:
      - '8080:8080'
    networks:
      - elk

networks:
  elk:
    driver: bridge
